### ISSUE TITLE
"`Tooltip` must be used within `TooltipProvider`"

### ISSUE THREAD

**Issue by Landarso** [Blookerss/mdpkm#2]
![image](https://user-images.githubusercontent.com/96104118/183480868-37ec3563-28cd-494a-ac97-ef80adc70333.png)
client.ts:16 [vite] connecting...
client.ts:53 [vite] connected.
react-dom.development.js:29742 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
three.module.js:50302 
        
       WARNING: Multiple instances of Three.js being imported.
(анонимный) @ three.module.js:50302
Error: readTextFile failed: Не удается найти указанный файл. (os error 2)
    at util.js:92:74
    at async skins.js:8:15
Promise.catch (асинхронно)
(анонимный) @ skins.js:8
Error: readTextFile failed: Не удается найти указанный файл. (os error 2)
    at util.js:92:74
    at async accounts.js:6:18
Promise.catch (асинхронно)
(анонимный) @ accounts.js:6
Error: readTextFile failed: Не удается найти указанный файл. (os error 2)
    at util.js:92:74
    at async settings.js:6:18
Promise.catch (асинхронно)
(анонимный) @ settings.js:6
4createContext.tsx:72 
        
       Uncaught Error: `Tooltip` must be used within `TooltipProvider`
    at useContext (createContext.tsx:72:13)
    at $a093c7e1ec25a057$export$28c660c63b792dea (Tooltip.tsx:163:27)
    at renderWithHooks (react-dom.development.js:16175:18)
    at mountIndeterminateComponent (react-dom.development.js:20913:13)
    at beginWork (react-dom.development.js:22416:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4161:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:16)
    at invokeGuardedCallback (react-dom.development.js:4274:31)
    at beginWork$1 (react-dom.development.js:27405:7)
    at performUnitOfWork (react-dom.development.js:26513:12)
useContext @ createContext.tsx:72
$a093c7e1ec25a057$export$28c660c63b792dea @ Tooltip.tsx:163
renderWithHooks @ react-dom.development.js:16175
mountIndeterminateComponent @ react-dom.development.js:20913
beginWork @ react-dom.development.js:22416
callCallback2 @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27405
performUnitOfWork @ react-dom.development.js:26513
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
performConcurrentWorkOnRoot @ react-dom.development.js:25694
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:86 
        
       Warning: Received `true` for a non-boolean attribute `horizontal`.

If you want to write it to the DOM, pass a string instead: horizontal="true" or horizontal={value.toString()}.
    at span
    at Styled.span
    at Typography (http://localhost:3000/voxeliface/components/Typography/index.jsx:37:18)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at newFunction (http://localhost:3000/src/common/plugins/patcher.js:8:25)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at PageItem (http://localhost:3000/src/components/Pages/Item.jsx:22:3)
    at div
    at http://localhost:3000/node_modules/.vite/deps/react-spring.js?v=0da3dde0:1093:50
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at Pages (http://localhost:3000/src/components/Pages/index.jsx:23:3)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at NavigationItem (http://localhost:3000/voxeliface/components/SideNavigation/Item.jsx:22:3)
    at div
    at http://localhost:3000/node_modules/.vite/deps/react-spring.js?v=0da3dde0:1093:50
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at SideNavigation (http://localhost:3000/voxeliface/components/SideNavigation/index.jsx:53:3)
    at main
    at Styled.main
    at Main (http://localhost:3000/voxeliface/components/Main.jsx:38:3)
    at ErrorBoundary2 (http://localhost:3000/node_modules/.vite/deps/react-error-boundary.js?v=0da3dde0:41:35)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at TauriApp (http://localhost:3000/voxeliface/components/App/Tauri.jsx:28:3)
    at t2 (http://localhost:3000/node_modules/.vite/deps/react-socks.js?v=0da3dde0:376:14)
    at App (http://localhost:3000/src/components/App.jsx:25:17)
    at newFunction (http://localhost:3000/src/common/plugins/patcher.js:8:25)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1120:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1067:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1196:5)
    at Provider (http://localhost:3000/node_modules/.vite/deps/react-redux.js?v=0da3dde0:1215:3)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:3762
warnUnknownProperties @ react-dom.development.js:3800
validateProperties$2 @ react-dom.development.js:3824
validatePropertiesInDevelopment @ react-dom.development.js:9538
setInitialProperties @ react-dom.development.js:9827
finalizeInitialChildren @ react-dom.development.js:10947
completeWork @ react-dom.development.js:19421
completeUnitOfWork @ react-dom.development.js:26552
performUnitOfWork @ react-dom.development.js:26524
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
performConcurrentWorkOnRoot @ react-dom.development.js:25694
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
4createContext.tsx:72 
        
       Uncaught Error: `Tooltip` must be used within `TooltipProvider`
    at useContext (createContext.tsx:72:13)
    at $a093c7e1ec25a057$export$28c660c63b792dea (Tooltip.tsx:163:27)
    at renderWithHooks (react-dom.development.js:16175:18)
    at mountIndeterminateComponent (react-dom.development.js:20913:13)
    at beginWork (react-dom.development.js:22416:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4161:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:16)
    at invokeGuardedCallback (react-dom.development.js:4274:31)
    at beginWork$1 (react-dom.development.js:27405:7)
    at performUnitOfWork (react-dom.development.js:26513:12)
useContext @ createContext.tsx:72
$a093c7e1ec25a057$export$28c660c63b792dea @ Tooltip.tsx:163
renderWithHooks @ react-dom.development.js:16175
mountIndeterminateComponent @ react-dom.development.js:20913
beginWork @ react-dom.development.js:22416
callCallback2 @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27405
performUnitOfWork @ react-dom.development.js:26513
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
recoverFromConcurrentError @ react-dom.development.js:25806
performConcurrentWorkOnRoot @ react-dom.development.js:25706
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
2react-dom.development.js:18572 
        
       The above error occurred in the <Tooltip> component:

    at $a093c7e1ec25a057$export$28c660c63b792dea (http://localhost:3000/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=0da3dde0:93:11)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at SideNavigation (http://localhost:3000/voxeliface/components/SideNavigation/index.jsx:53:3)
    at main
    at Styled.main
    at Main (http://localhost:3000/voxeliface/components/Main.jsx:38:3)
    at ErrorBoundary2 (http://localhost:3000/node_modules/.vite/deps/react-error-boundary.js?v=0da3dde0:41:35)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at TauriApp (http://localhost:3000/voxeliface/components/App/Tauri.jsx:28:3)
    at t2 (http://localhost:3000/node_modules/.vite/deps/react-socks.js?v=0da3dde0:376:14)
    at App (http://localhost:3000/src/components/App.jsx:25:17)
    at newFunction (http://localhost:3000/src/common/plugins/patcher.js:8:25)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1120:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1067:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1196:5)
    at Provider (http://localhost:3000/node_modules/.vite/deps/react-redux.js?v=0da3dde0:1215:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary2.
logCapturedError @ react-dom.development.js:18572
callback @ react-dom.development.js:18640
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23263
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
2react-dom.development.js:18572 
        
       The above error occurred in the <Tooltip> component:

    at $a093c7e1ec25a057$export$28c660c63b792dea (http://localhost:3000/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=0da3dde0:93:11)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at SideNavigation (http://localhost:3000/voxeliface/components/SideNavigation/index.jsx:53:3)
    at main
    at Styled.main
    at Main (http://localhost:3000/voxeliface/components/Main.jsx:38:3)
    at ErrorBoundary2 (http://localhost:3000/node_modules/.vite/deps/react-error-boundary.js?v=0da3dde0:41:35)
    at div
    at Styled.div
    at Grid (http://localhost:3000/voxeliface/components/Grid.jsx:29:20)
    at TauriApp (http://localhost:3000/voxeliface/components/App/Tauri.jsx:28:3)
    at t2 (http://localhost:3000/node_modules/.vite/deps/react-socks.js?v=0da3dde0:376:14)
    at App (http://localhost:3000/src/components/App.jsx:25:17)
    at newFunction (http://localhost:3000/src/common/plugins/patcher.js:8:25)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1120:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1067:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=0da3dde0:1196:5)
    at Provider (http://localhost:3000/node_modules/.vite/deps/react-redux.js?v=0da3dde0:1215:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary2.
logCapturedError @ react-dom.development.js:18572
callback @ react-dom.development.js:18640
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23263
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533

**Comment by Blookerss** [comment]
hello, thanks for opening the first issue!
i was unable to reproduce this error myself, could you follow up with reproduction steps?

**Comment by Landarso** [comment]
Hello, after installing dependencies using npm i, I got a message about the absence of some libraries, after installing them manually through the same npm, I get this error.
[console_log.txt](https://github.com/Blookerss/mdpkm/files/9289117/console_log.txt)

**Comment by Blookerss** [comment]
You need to run `npm install` in the `voxeliface` directory.
additionally, i recommend using **yarn** instead of **npm**!

**Comment by Landarso** [comment]
Thanks, it works!!!
